### ISSUE TITLE
tcsetpgrp issue

### ISSUE THREAD

**Issue by ryniker** [minoca/os#82] opened 2016-12-07 23:45 UTC
bash carefully manages process groups to implement job control features.  It uses POSIX-
defined functions for this purpose, but fails in minoca.  I enabled a detailed error message
in my build, and see this:

bash-4.4$ cmd/bash -i
bash: tcsetpgrp(255) failed: pid 60166 to pgrp 60166 : Operation not supported
bash: cannot set terminal process group (60126): Operation not supported
bash: no job control in this shell
bash-4.4$ exit
exit
bash: tcsetpgrp(255) failed: pid 60166 to pgrp 60126 : Operation not supported
bash-4.4$ 

Is this possibly a case of tcsetpgrp is documented, but not fully  implemented (or perhaps
does not conform to the POSIX specification) or is this supposed to work?

**Comment by evangreen** [comment] 2016-12-08 01:31
That is supposed to work. Are you sure what you're operating on is a terminal? `test -t 0 || echo not a terminal`.

Do you see this on the bash from opkg?

**Comment by ryniker** [comment] 2016-12-08 02:04
>Do you see this on the bash from opkg?

Yes, same thing... but not the detailed error message that I enabled in
my build.  But I am glad to learn this is supposed to work.

bash-4.4$ /usr/bin/bash --version
GNU bash, version 4.3.30(1)-release (arm-none-minoca)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
bash-4.4$ /usr/bin/bash -i
bash: cannot set terminal process group (60126): Operation not supported
bash: no job control in this shell
bash-4.3$

**Comment by evangreen** [comment] 2016-12-13 01:36
I started to take a look here, but I'm having trouble reproducing it with the latest sources:
```
~# opkg install bash
Installing bash (4.3.30) on root.
Downloading http://www.minocacorp.com/packages/0.3/i686/main/bash_4.3.30_minoca-i686.ipk.
Configuring bash.
~# bash
bash-4.3# su evan
/root$ bash
bash-4.3$ cd
bash-4.3$ ls
bash-4.3$ ls -la
total 24
drwxr-sr-x  1 evan evan  4096 Dec 12 17:29 .
drwxrwxr-x  1 root root  4096 Dec 12 17:28 ..
-rw-------  1 evan evan    53 Dec 12 17:29 .bash_history
bash-4.3$
```

I noticed your output above has cmd/bash -i. Is it possible that things are scripted such that bash is being launched without its stdin/out pointed at a terminal device? Is this from inside emacs or something?

**Comment by ryniker** [comment] 2016-12-13 12:20
>I noticed your output above has cmd/bash -i

The "-i" argument tells bash the caller wants an interactive shell.  I
believe bash only constructs its job control facilities for interactive
shells, where there is presumably a person who might wish to interrupt a
task, suspend it, etc.

**Comment by evangreen** [comment] 2016-12-13 17:12
Usually bash or sh figures out on its own whether it's speaking to a human by running something like `isatty(STDIN_FILENO)`. In a correct world you wouldn't need to specify -i, since bash would have guessed that on its own.

Before I started fixing the reported issues in emacs, emacs was having trouble creating a PTY as a non-root user. So it was falling back to implementing the interactive shell support with a pipe. If the bash issues you're mentioning were occurring inside one of these emacs sessions, then bash wouldn't be interacting with a terminal, which would explain this behavior. I made changes to both the "os" repository and the emacs diff at https://gitlab.com/minoca/third-party/blob/master/build/emacs-24.5/emacs-24.5.diff . 

If you were just launching bash straight from sh, it would be interesting to verify that stdin is a terminal both before and after bash is launched by running something like `test -t 0 || echo not a terminal`.

**Comment by ryniker** [comment] 2016-12-13 22:06
Evan, you are right, bash will automatically conclude it is interactive
with a suitable terminal file.  When invoked directly:

  ~$ cmd/bash
  bash-4.4$ test -t 0
  bash-4.4$ echo $?
  0
  bash-4.4$ echo $TERM
  xterm-256color

When invoked from emacs:

  bash-4.4$ echo $TERM
  dumb
  bash-4.4$ test -t 0
  bash-4.4$ echo $?
  1

This is not odd; I see the same thing when I run emacs under Linux.  In a
shell buffer, TERM=dumb.  Nevertheless, job control works well.

The symptom in Minoca is the complaint from bash about failure in
tcsetpgrp.  I see this definition for tcsetpgrp in
os/apps/libc/dynamic/termios.c:679

    return ioctl(FileDescriptor, TIOCSPGRP, &Identifier);

which is what most Unix-like systems do.

I cannot find any other reference to TIOCSPGRP in the .c files in
Minoka's os/ tree.  Is this another case where a library function
provides an interface to nothing - tcsetpgrp simply is not implemented?

Well, Rome was not built in a day.  The problem I see is many
applications use tools such at autoconf (or they have their own build
logic) to check whether functions such as tcsetpgrp (and statvfs - Issue
48) are available so they can adapt to their execution environment.  This
leads to trouble when the functions exist, but are not implemented.

If one is lucky, the damage is limited to error messages and erratic
behavior by Minoca.  If one is unlucky, there could be unobserved
failures, data loss, and problems that are very difficult to understand.

"Minoca provides a mostly POSIX compliant implementation of the C
library." is misleading if it means the library functions exist, but they
may not be implemeneted, or not implemented to the POSIX standard.

**Comment by evangreen** [comment] 2016-12-14 22:21
This one's throwing me for a loop, mostly because it should work. TIOCSPGRP is defined at os/apps/libc/include/sys/ioctl.h, line 144. The kernel definition is at include/minoca/kernel/io.h, line 982. The implementation is in kernel/io/pty.c at line 2290. 

The only return values from that ioctl are EPERM, ENOTTY, or errors related to IopTerminalUserBufferCopy or IopTerminalValidateGroup. ENOTSUP shouldn't show up. But we do send back ENOTSUP in IoUserControl, line 2714 of kernel/io/iobase.c, if the descriptor being operated on is not a terminal.

I think I need more detailed repro steps here. If I have a fresh Minoca instance, can I just do `opkg update; opkg install bash; bash` to see the tcsetpgrp error? Or is there something else I need to do to observe the error? Is there a particular revision you're on, or is it the latest?

Apologies for all the back and forth.

**Comment by evangreen** [comment] 2017-05-18 20:50
I believe the underlying issue here was that somehow the shell was being served via something other than a pseudo-terminal (like a pipe). I could never quite nail down what the ssh or installation config was here to make that happen. Closing this for now for lack of more information.

**Closed by evangreen** 2017-05-18 20:50 UTC

**Comment by ryniker** [comment] 2017-05-19 13:37
Try in an emacs shell buffer.  During emacs build, configure detects tcsetpgrp is available and therefore emacs uses it in its code for shell buffers.  Minoca allows the tcsetpgrp call, but does not implement the function.

I treated the symptom - edited emacs' configure output to make it show tcsetpgrp is not available.

To fix the problem, either minoca should add code to support this operation (best strategy), minoca could remove its stub code so applications might understand this function does not exist, or build tools like autoconf could be enhanced to understand minoca as a distinct target system.  I think this last option is bad at this time, because minoca changes frequently as new capabilities are added.  Once a more stable definition of minoca is achieved, this might be appropriate.

If emacs is the only known place this problem occurs, perhaps documentation is the answer - provide minoca users who want to build emacs with information about a kink (manual intervention) needed in the build process until minoca supports this function.

**Comment by evangreen** [comment] 2017-05-19 18:28
We do have tcsetpgrp now. I think while spawning its shell emacs failed to create a pseudoterminal, so it fell back to using pipes to communicate with the shell. tcsetpgrp doesn't work if your stdin isn't a terminal (and is for instance a pipe). I fixed the issue that was preventing emacs from creating pseudoterminals, so I think this should be fixed in the latest [nightlies](https://www.minocacorp.com/download/nightlies/latest-x86). If you do give the nightlies a try, don't forget to edit /etc/opkg/opkg.conf to point at `http://www.minocacorp.com/download/nightlies/latest-x86/0.4/i686/main`.
