### ISSUE TITLE
socket input limit

### ISSUE THREAD

**Issue by bronozoj** [minoca/os#58] opened 2016-11-16 23:45 UTC
I have been coding in c for minoca for about a week, and I have noticed that the functions for receiving data from socket connections (recv, recvfrom, recvmesg) seems to have an internal buffer limit of 256 bytes even if i specify a buffer larger than that (1 - 10kb) does it have something to do with the network drivers or is it a limitation of the glibc port?

**Comment by ccstevens** [comment] 2016-11-17 00:10
Interesting find. I don't see any limits set in the C library, other than making sure the length supplied to recv is less than or equal to SSIZE_MAX - this is necessary as recv returns an ssize_t value. In the drivers, we default the internal receive buffer on UDP to 256k and the TCP receive window to 64k. If you're using UDP, the receive routine is supposed to return as soon as it gets any data. Same with TCP unless MSG_WAITALL is supplied.

So, a few questions to clarify what you're seeing:
- Are you determining this 256 byte limit based on the number of received bytes reported from recv?
- By "specify a buffer larger" you mean that you're just giving recv a buffer with length of 10k?
- What protocol are you using? UDP or TCP?
- Have you tried setting the SO_RCVBUF socket option?
- How are you sending the data to Minoca? Any chance it's getting batched in 256 byte chunks along the way, causing the receive routines to always exit with 256 bytes of data?

**Comment by bronozoj** [comment] 2016-11-17 00:17
ive read that socket option and tried setting it as well but the problem persists. I work on a raspberry pi 2 and web browsers are my client since i am developing a homebrew httpd client to upload/download files to the pi. I use tcp. my code runs on linux and does not encounter the same problem it does on minoca

**Comment by ccstevens** [comment] 2016-11-17 00:25
Ok. I should be able to repro that set-up locally.

**Comment by ccstevens** [comment] 2016-11-17 02:52
Unfortunately, I'm not able to repro this on a raspberry pi 3 (pi 2 is tied up in a build right now). My very simple setup is to have my dev box play the server and the pi 3 play the client. I created sockets on each in python, connected and sent 1024 bytes to the pi 3 client, which received all 1024 bytes with one recv. I also reproduced receiving 1024 bytes with a simple C app. This says to me that there is nothing artificial in there limiting recv to 256 bytes.

I also instrumented the kernel to track sizes returned from NetpTcpReceive and downloaded a 16MB file via `wget`. It didn't return from any calls with less than 256 bytes. `wget` appears to be using `read` rather than `recv`, but they boil down to the same driver call. 

So, back to the drawing board. Are there any additional details or steps you think I should consider to reproduce this? That is, is your code doing anything fancy besides calling `socket()`, `connect()`/`accept()` and `recv()`? Is it possible to send me a binary (or code) to try? (chris@minocacorp.com)

The pi 2 is obviously slower than the pi 3, so I'm building an armv6 image to see what happens on the pi 1 on the chance that we're just not churning through packets fast enough.

**Comment by bronozoj** [comment] 2016-11-17 14:01
I have retested as well here and the problem seems to have disappeared a bit. But there are rare occasions where the packets received are capped to 256 and the rest of the packets seem to have been thrown away in the process

**Comment by bronozoj** [comment] 2016-11-17 14:19
[code.c.txt](https://github.com/minoca/os/files/597556/code.c.txt)
here is the code im using. when i use a blocking recv, it returns only 256 bytes all the time.
so i devised a function recv_wrapper that makes it non-blocking to get the rest of the bytes (prone to loops)

this almost never happens when the code is compiled to linux. then again, if i continue calling recv to the socket, it throws out more data.

**Comment by drawkula** [comment] 2016-11-17 14:40
I got problems with SSH when transferring larger amounts of data, e.g. using SCP, RSYNC over SSH or GIT over SSH.

This may be related.
```
(root@minoca:pty19)/src/third-party# git branch
  add-build-ccache-3.3.3
* master
(root@minoca:pty19)/src/third-party# git remote -v
origin  git@gitlab.com:yeti/minoca--third-party.git (fetch)
origin  git@gitlab.com:yeti/minoca--third-party.git (push)
upstream        git@gitlab.com:minoca/third-party.git (push)
upstream        git@gitlab.com:minoca/third-party.git (fetch)
(root@minoca:pty19)/src/third-party# git fetch upstream
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (24/24), done.
fatal: protocol error: bad line length character: ACK
fatal: early EOFs:  79% (19/24)   
fatal: unpack-objects failed
```
...or:
```
(root@minoca:pty19)/tmp# scp yeti@HIDDEN:html/files/micronucleus/20160213-091449-CET--digispark-mouse-move-only.webm .                                
20160213-091449-CET--digispark-mouse-move-only.webm                100%  323KB 323.0KB/s   00:00    
��;ýýýO$ýý-ý)ý9ý┴"'ý°'␤≤ýýýý9ý␊ýý!
                                  £ýýýHýýID\␊ýý[ýýVýIýýV⎽ýYý1ý
                                                              8 UXNýVý┬Výýý◆ýýýý│@Oýýý≠⎽ýYýý␤<┴Ôýýý⎽ýUý=ýýý≤L:6G[K?ýýýýZýýý5£°⎺ýUýý£ýýýý≠Pýýýýý_└.ýý│Gýýý␋Aý0ýýýJ%ýDýQ(ýýýýý#8A3ýýý▒6ýG#ý≠@ý
(⎼⎺⎺├@└␋┼⎺␌▒:⎻├≤19)/├└⎻# 
```
Even pure SSH shell sessions die... but it takes longer. When scrolling a lot, they die faster. I thought it'd be a "Minoca in Qemu" problem, but this issue might fit my problems too...

**Comment by ccstevens** [comment] 2016-11-18 01:33
@bronozoj Thanks for sharing your code! I immediately got a repro and was able to track it down. We were sending a scaled TCP window size (256 << 8) in our SYN packets, rather than the required raw size. So, the client was interpreting that as a window size of 256 bytes (not 64K) and truncating the first HTTP packet to 256 bytes. This is fixed with [28ac1988](https://github.com/minoca/os/commit/28ac198801516c656dd03ae2b7185d6dc11a3d8d).

@drawkula Not sure if this would explain your issues. I'll try to reproduce those next.

**Comment by ccstevens** [comment] 2016-11-23 03:02
@drawkula I just pushed change [4e4eea96](https://github.com/minoca/os/commit/4e4eea96be5c2e0a23c7f571398a735c1a2248f0) that fixes the `scp` issue for me. It ended up being a pipe I/O bug.

I didn't try to reproduce the `git fetch upstream` bug yet. But it may very well be the same issue if `git` is using pipes. Also not sure if this will solve the "even pure SSH shell sessions die" issue you're seeing, but it might. Anyway, if you get a chance to give the fix a try, let me know if you're still hitting any issues.

**Comment by drawkula** [comment] 2016-11-23 14:10
```
(root@minoca:pty1)/tmp# scp yeti@HIDDEN:html/files/micronucleus/20160213-091449-CET--digispark-mouse-move-only.webm
20160213-091449-CET--digispark-mouse-move-only.webm                 100%  323KB 161.5KB/s   00:02
```
\o/ Party! \o/

`ssh` connections still die. I got the feeling that the amount or speed of I/O has impact on this, e.g. my `ssh` connection just died while doing `zcat gcc-4.9.2.tar.gz | tar tv`. Massive scrolling with editors or `less` or just `cat`ing long texts seems to trigger it sometimes.
```
(root@minoca:pty2)/src/third-party# git fetch upstream            
From gitlab.com:minoca/third-party
   1e8f72e..6536f39  master     -> upstream/master
```
Probably better now too but having updated the repository via http some hours ago, there was nothing to fetch but the connection over `ssh` worked and that's more than before. I need to keep an eye on `git` over `ssh` a bit longer...

**Comment by ccstevens** [comment] 2016-12-02 19:39
@bronozoj Did you get a chance to see if this fix made your problems go away?

**Comment by ccstevens** [comment] 2016-12-07 18:38
Closing this out as I could not reproduce the issue after change [28ac1988](https://github.com/minoca/os/commit/28ac198801516c656dd03ae2b7185d6dc11a3d8d).

**Closed by ccstevens** 2016-12-07 18:38 UTC
